Repository axibase/atsd-api-test, pull requests merged in 2018-08, with the labels that each got.

#506 5494: Add a big query to test WHERE and HAVING is_weekday()
  src/test/java/com/axibase/tsd/api/method/sql/SqlTest.java
  src/test/java/com/axibase/tsd/api/method/sql/clause/where/SqlWhereIsWeekdayTest.java
Labels: pr: review :eyes:

#505 5490: Add test for mathematical operators in time functions
  src/test/java/com/axibase/tsd/api/method/sql/function/date/SqlTimeArithmeticTest.java
Labels: pr: review :eyes:, work is done :gift:

#465 SQL: Interpolation previous with fill=false #4814
  src/test/java/com/axibase/tsd/api/method/sql/function/interpolate/FullInterpolationTest.java
Labels: work is done :gift:

#511 5542: Add WITH TIMEZONE tests
  src/main/java/com/axibase/tsd/api/model/series/Sample.java
  src/main/java/com/axibase/tsd/api/model/series/Series.java
  src/test/java/com/axibase/tsd/api/method/sql/clause/with/SqlWithTimezoneTest.java
Labels: work is done :gift:
